# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 16.0
org_name: La Cigogne - Bar à jeux
org_slug: cigogne-jeux
rebel_module_groups: []
repo_description: ''
repo_name: Odoo addons for La cigogne - Bar à jeux
repo_slug: cigogne-odoo-addons
repo_website: https://github.com/cigogne-jeux/cigogne-odoo-addons
travis_apt_packages: []
travis_apt_sources: []

